name: OIDC Authentication
on: [push]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  ConnectToAWS:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654763947810:role/GitHubActionsWorkflowRole # role ARN
          aws-region: us-east-1

      - name: Test Connection
        run: aws sts get-caller-identity
